#!/bin/bash

export PATH=$DEVKITPATH/devkitA64/bin:$PATH
TARGET_TRIPLE=aarch64-none-elf

echo "Starting new build."

unset CARGO_INCREMENTAL
RUST_TARGET_PATH="$PWD" xargo build --release --target=$TARGET_TRIPLE --verbose

echo "Compiled rust target."

echo "Linking rust target with: aarch64-none-elf-gcc -g -march=armv8-a -mtune=cortex-a57 -mtp=soft -static -Wall -ffunction-sections -DSWITCH -specs=/opt/devkitpro/libnx/switch.specs -L /opt/devkitpro/libnx/lib/ -L /opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.2.0/ -L /opt/devkitpro/devkitA64/aarch64-none-elf/lib/pic/ -L target/aarch64-horizon-elf/release/ -lc -lnx -lgcc -lc -lsysbase target/aarch64-none-elf/release/liblibnx_rs_template.a -lm -lc -lgcc -lc -lnx -lc -lsysbase -lc -lgcc -lc -o test.elf --verbose -nodefaultlibs -Wl,-z,text"
aarch64-none-elf-gcc -g -march=armv8-a -mtune=cortex-a57 -mtp=soft -static -Wall -ffunction-sections -DSWITCH -specs=/opt/devkitpro/libnx/switch.specs -L /opt/devkitpro/libnx/lib/ -L /opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.2.0/ -L /opt/devkitpro/devkitA64/aarch64-none-elf/lib/pic/ -L target/aarch64-horizon-elf/release/ -lc -lnx -lgcc -lc -lsysbase target/aarch64-none-elf/release/liblibnx_rs_template.a -lm -lc -lgcc -lc -lnx -lc -lsysbase -lc -lgcc -lc -o test.elf --verbose -nodefaultlibs -Wl,-z,text

echo "Building NRO with: elf2nro test.elf testa.nro"
elf2nro test.elf testa.nro