#!/bin/bash

export TARGET=aarch64-none-elf
export TARGET_CC="aarch64-none-elf-gcc"
export TARGET_CXX="aarch64-none-elf-g++"
export PATH=$DEVKITPATH/devkitA64/bin:$PATH
export TARGET_CFLAGS="\
 -fPIC\
 -g\
 -march=armv8-a -mtune=cortex-a57 -mtp=soft\
 -Wall\
 -specs=/opt/devkitpro/libnx/switch.specs\
\
 -L /opt/devkitpro/libnx/lib\
 -L /opt/devkitpro/devkitA64/lib/gcc/aarch64-none-elf/8.2.0/pic\
 -L /opt/devkitpro/devkitA64/aarch64-none-elf/lib/pic\
\
 -Wl,-z,text\
 -Wl,--gc-sections\
 -Wl,--emit-relocs\
 -Wl,--eh-frame-hdr\
\
 -nostartfiles\
 -nodefaultlibs\
 -nostdlib\
\
 -O0\
"

export TARGET_CXXFLAGS="$TARGET_CFLAGS -fno-rtti -fno-exceptions -std=gnu++11"
export TARGET_LDFLAGS="-specs=/opt/devkitpro/libnx/switch.specs"
TARGET_TRIPLE=aarch64-none-elf

echo "Starting new build."\
 &&\
 CARGO_INCREMENTAL=0\
 RUST_TARGET_PATH="$PWD"\
 RUST_BACKTRACE=1\
 xargo build --release --bin libnxbin --target=$TARGET_TRIPLE --verbose --features="conrod-test"\
 &&\
 echo "Compiled rust target. Now creating nro."\
 &&\
 elf2nro target/aarch64-none-elf/release/libnxbin.nx_elf libnxbin.nro\
 &&\
 echo "Finished making nro."