[dependencies.core]
stage = 0

[dependencies.alloc]
stage = 1

[dependencies.rand]
stage = 2
git = "https://github.com/rust-lang-nursery/rand"
default-features = false

[dependencies.libc]
stage = 3
default-features=false 

[dependencies.std]
path = "../ctr-std-horizon/src/libstd"
stage = 4