#!/bin/bash
echo "Starting new build."\
 &&\
 CARGO_INCREMENTAL=0\
 RUST_TARGET_PATH="$PWD"\
 RUST_BACKTRACE=1\
 xargo build --release --bin libnxbin --target=aarch64-none-elf --verbose --features="sysmodule-test" \
 &&\
 echo "Compiled rust target. Now creating nso."\
 &&\
 elf2nso target/aarch64-none-elf/release/libnxbin.nx_elf testmodule.nso\
 &&\
 echo "Finished making nso."